name = "Feather"
author = "SamLolo"
version = "3.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6fc572208d1b07160f5c000c77bbd090d6b30708688fc61165b491d4021a1301"

[versions]
fabric = "0.16.14"
minecraft = "1.21.2"

[options]
acceptable-game-versions = ["1.21.1"]
