name = "Feather"
version = "V3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d57f99d51e3a4c425bb0cd3a358c4fdace6c960a0459a8c53587e974159dc476"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
