name = "Feather"
author = "SamLolo"
version = "3.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53a10b13f1b2ed1c34e1922403218f5da97f3e53efd858db59ba65acc6d25fdc"

[versions]
fabric = "0.16.14"
minecraft = "1.21.2"

[options]
acceptable-game-versions = ["1.21.1"]
