name: 'Parse Modpack | Action'
description: 'Parses a modpacks pack file'

inputs:
  directory:
    description: 'Path to the modpack directory'
    required: true
  pack-file:
    description: 'Path to the pack config file'
    required: false
    default: 'pack.toml'

outputs:
  loader:
    description: 'Detected mod loader'
    value: ${{ steps.parse.outputs.loader }}
  game-version:
    description: 'Detected game version'
    value: ${{ steps.parse.outputs.game-version }}

runs:
  using: 'composite'

  steps:

    - name: Check Out Git Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: 'main'

    - name: Parse the pack.toml
      id: parse
      run: |
        loaders=("fabric" "forge" "quilt" "neoforge")
        for loader in "${loaders[@]}"; do
          if [[ ${{ inputs.directory }} == *"$loader"* ]]; then
            LOADER="$loader"
            break
          fi
        done
        [[ -z "$LOADER" ]] && { echo "::error file=${{ inputs.directory }}::No match found for loaders in ${{ inputs.pack-file }}" && exit 1; }

        GAME_VERSION=$(grep -oP 'minecraft = "\K[^"]+' "${{ inputs.pack-file }}")
        echo "loader=$LOADER"
        echo "game-version=$GAME_VERSION"
      shell: bash
      working-directory: ${{ inputs.directory }}

    
    - name: Output detected loader and game version.
      run: |
        echo "The detected loader for '${{ inputs.directory }}' is '${{ steps.parse.outputs.loader }}'"
        echo "The detected game version for '${{ inputs.directory }}'' is '${{ steps.parse.outputs.game-version }}'"
      shell: bash
