#Fabrishot screenshot config
#Sun Jun 23 10:38:45 BST 2024
custom_file_name=huge_%time%
delay=3
disable_gui_scaling=false
file_format=PNG
height=2160
hide_hud=false
override_screenshot_key=false
save_file=true
width=3840
