name = "Feather"
author = "SamLolo"
version = "3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9713d7b52779f82c07d2446ffb3e293587af385a1d83b3d72b2f37a5c61d3c72"

[versions]
fabric = "0.16.9"
minecraft = "1.21"
