name = "Feather"
author = "SamLolo"
version = "3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd6c7ee70909c542561dda00ae04f38d4300f564ad37bef38386cb5027eddda6"

[versions]
fabric = "0.16.9"
minecraft = "1.21"
