name = "Feather"
author = "SamLolo"
version = "3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "235c254a73b201cab9ea90152df182bd60d474bba8b943d0096401c281425595"

[versions]
fabric = "0.16.10"
minecraft = "1.21"
