# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[changelog]
# A Tera template to be rendered as the changelog.
# See https://keats.github.io/tera/docs/#introduction
header = """
## What's New?
"""

body = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        {% if commit.scope == "temp" %}
          - {{ commit.message | split(pat="\n") | first | upper_first | trim }} [TEMP]
        {% else %}
          - {{ commit.message | split(pat="\n") | first | upper_first | trim }}
        {% endif %}
    {% endfor %}
{% endfor %}\n
"""

footer = """
This format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/).
"""
# Remove leading and trailing whitespaces from the changelog's body.
trim = true

[git]
# Parse commits according to the conventional commits specification.
# See https://www.conventionalcommits.org
conventional_commits = true
filter_unconventional = true

# An array of regex based parsers to modify commit messages prior to further processing.
commit_preprocessors = [
  # Remove issue numbers.
  { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "" },
]

# An array of regex based parsers for extracting data from the commit message.
# Assigns commits to groups.
# Optionally sets the commit's scope and can decide to exclude commits from further processing.
commit_parsers = [
  { message = '^[a|A]dd(?:\(.+\))?:\s', group = "Added" },
  { message = '^[r|R]emove(?:\(.+\))?:\s', group = "Removed" },
  { message = '^[c|C]hore(?:\(.+\))?:\s', group = "Changed" },
  { message = '^[f|F]ix(?:\(.+\))?:\s', group = "Changed" },
]

# Exclude commits that are not matched by any commit parser.
filter_commits = true

# Order releases topologically instead of chronologically.
topo_order = false

# Order of commits in each group/release within the changelog.
# Allowed values: newest, oldest
sort_commits = "newest"

[remote.github]
# Contains Git remote relatedd configuration
owner = "SamLolo"
repo = "Feather"