name = "Feather"
author = "SamLolo"
version = "v2.1-alpha"
description = "A lightweight fabric modded client packed full of vanilla-like features and performance improvements that will make your minecraft experience that little bit better!"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6642304462cc6cb4f4d380a43a385e6341b87966e5c9d028b9caf38e42f7bb9b"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
