name = "Feather"
author = "SamLolo"
description = "A lightweight fabric modded client packed full of vanilla-like features and performance improvements that will make your minecraft experience that little bit better!"
version = "2.1-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c9382a073babf6b38a5ca0e598f68e93cb64e9df0ab29200484ab697c50efa8"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
