name = "Feather"
author = "SamLolo"
version = "v2.1.2"
description = "A lightweight fabric modded client packed full of vanilla-like features and performance improvements that will make your minecraft experience that little bit better!"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "204257d58bc39a9fef1e36d39116b6df22a484e547c15073481fef3528ff34e9"

[versions]
fabric = "0.14.22"
minecraft = "1.20.2"

[options]
acceptable-game-versions = ["1.20.2"]
