name = "Feather"
author = "SamLolo"
version = "v2.1.1"
description = "A lightweight fabric modded client packed full of vanilla-like features and performance improvements that will make your minecraft experience that little bit better!"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eca6ad814c3dfe1a633ee9769ca0d24035f126b3e0486c37c758313d6b8e9b2a"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
