#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Jul 07 19:00:44 BST 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
