name = "Feather"
author = "SamLolo"
version = "3.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5990d6974edd9e67bec4890b513b727057e45e0d6f24c3e9f180a0a98213782c"

[versions]
minecraft = "1.21.1"
quilt = "0.28.1"
