name = "Feather"
author = "SamLolo"
version = "3.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fc08535a2cfb1b472a243cf5ef09472e41120dd108b1b84a03702b6766447c9"

[versions]
minecraft = "1.21.1"
quilt = "0.29.1-beta.1"
