name = "Feather"
author = "SamLolo"
version = "3.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ec6f146d9a4c1bdb613a27ecd9aaf305cd44856a289a34423f070ebb6adcc0f"

[versions]
minecraft = "1.21.1"
quilt = "0.28.1"
