name = "Feather"
author = "SamLolo"
version = "3.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06c7e0393fc76894bd390cab78c7798ecb08c856ef13b790b74892a701bcaa5a"

[versions]
minecraft = "1.21.1"
quilt = "0.28.1"
