#Configuration file for Enhanced Block Entities
#Sun Jun 23 13:28:41 BST 2024
bed_ao=true
bell_ao=true
chest_ao=true
christmas_chests=allowed
decorated_pot_ao=true
experimental_beds=false
experimental_chests=false
experimental_signs=false
force_resource_pack_compat=false
render_enhanced_beds=true
render_enhanced_bells=true
render_enhanced_chests=true
render_enhanced_decorated_pots=true
render_enhanced_shulker_boxes=false
render_enhanced_signs=true
shulker_box_ao=false
sign_ao=true
sign_text_rendering=smart
