name = "Feather"
author = "SamLolo"
version = "3.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d898b2dab7def0d91a5205170707d8e7114787a9cafd5f354b6418a857dbf26d"

[versions]
minecraft = "1.21.1"
quilt = "0.29.0"
