name = "Feather"
author = "SamLolo"
version = "3.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dccd414f48c998639c93be0daca118452599eb146dd88c480f757571e5e7556b"

[versions]
minecraft = "1.21.1"
quilt = "0.28.1"
