name = "Feather"
author = "SamLolo"
version = "3.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1854705e41ed98f470afa93ee25323ba3b5d34bfc4f86e79569625dd27d92409"

[versions]
minecraft = "1.21.1"
quilt = "0.29.0"
