name: Modpack Release

on:
  push:
    branches:
      - main

env:
  pack-file: 'pack.toml'
  default-release-modrinth: 'true'
  default-release-curseforge: 'true'


jobs:

  setup-release:
    name: Setup workflow environment
    runs-on: ubuntu-latest

    permissions:
      contents: read

    outputs:
      curseforge: ${{ steps.set-vendors.outputs.curseforge }}
      modrinth: ${{ steps.set-vendors.outputs.modrinth }}
      release-tag: ${{ steps.read-properties.outputs.release }}
    
    steps:
      
      - name: Set Mod Vendors
        id: set-vendors
        run: |
          [[ ! -z "${{ secrets.CURSEFORGE_TOKEN }}" && ! -z "${{ secrets.CURSEFORGE_ID }}" ]] && echo "curseforge=true" >> $GITHUB_OUTPUT || echo "curseforge=false" >> $GITHUB_OUTPUT
          [[ ! -z "${{ secrets.MODRINTH_TOKEN }}" && ! -z "${{ secrets.MODRINTH_ID }}" ]] && echo "modrinth=true" >> $GITHUB_OUTPUT || echo "modrinth=false" >> $GITHUB_OUTPUT
        shell: bash


      - name: Read Master JSON File
        id: read-json
        run: |
          echo ls
          content=`cat ./main/pack.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=content::$content"
        shell: bash
        working-directory: "."

        
      - name: Read Properties From JSON File
        id: read-properties
        run: |
          echo "release=${{ fromJson(steps.read-json.outputs.content).release }}"


  parse-modpacks:
    name: Parse modpacks to a list
    runs-on: ubuntu-latest

    permissions:
      contents: read

    outputs:
      modpack-folders: ${{ steps.list-modpacks.outputs.modpack-folders }}
    
    steps:

      - name: Check Out Git Repository
        uses: actions/checkout@v4

      - name: List Modpacks
        id: list-modpacks
        run: |
          modpackFolders=()
          while IFS= read -r -d '' folder; do
            if [ -e "$folder/pack.toml" ]; then
              modpackFolders+=("$folder")
            fi
          done < <(find client/ -type d -print0)
            
          echo "modpack-folders=$(jq --compact-output --null-input '$ARGS.positional' --args -- "${modpackFolders[@]}")" >> "$GITHUB_OUTPUT"
  
  
      - name: Print detected modpacks
        run: |
          echo "::notice:: Detected modpacks: ${{ steps.list-modpacks.outputs.modpack-folders }}"



  release-please:
    name: Handle Releases
    runs-on: ubuntu-latest

    needs:
      - setup-release
      - parse-modpacks
  
    if: ${{ (needs.parse-modpacks.outputs.modpack-folders) != '[]' }}

    strategy:
      fail-fast: false
      matrix:
        modpack: ${{ fromJson(needs.parse-modpacks.outputs.modpack-folders) }}

    defaults:
      run:
        working-directory: ${{ matrix.modpack }}

    permissions:
      contents: write
      pull-requests: write


    steps:      

      - name: Check Out Git Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Parse Pack File
        id: parse-pack
        uses: ./.github/actions/parse
        with:
          modpack: ${{ matrix.modpack }}
