name: Github Release
run-name: Release V${{ inputs.version }} for MC ${{ inputs.mc-version }} (@${{ github.actor }})

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Modpack Version'
        required: true
        type: string
      mc-version:
        description: 'Minecraft Version'
        required: true
        type: string
      type:
        description: 'Release Type'
        required: false
        default: release
        type: choice
        options:
          - release
          - beta
          - alpha


jobs:
  
  create-release:
    name: Create a new draft release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Draft Release
        run: |
          gh release create v${{ inputs.version }} \
            --draft \
            --title "Version ${{ inputs.version }} for MC ${{ inputs.mc-version }}" \
            --fail-on-no-commits \
            --repo ${{ github.repository }}

      - name: Set As Pre-Release
        if: ${{ inputs.type }} != 'release'
        run: |
          gh release edit v${{ inputs.version }} \
            --prerelease \
            --repo ${{ github.repository }}
      
      - name: Generate Changelog
        id: git-cliff
        uses: orhun/git-cliff-action@main
        with:
          config: cliff.toml
          args: -u --tag v${{ inputs.version }} --strip header
        env:
          OUTPUT: docs/CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Add Notes
        run: |
          gh release edit v${{ inputs.version }} \
            --notes-file docs/CHANGELOG.md \
            --repo ${{ github.repository }}

  
  build-artifacts:
    name: Build & add files
    runs-on: ubuntu-latest
    
    needs:
      - create-release

    permissions:
      contents: write

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        platform: ['curseforge', 'modrinth']
        loader: ['fabric', 'quilt']

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - name: Build Packwiz
        run: go install github.com/packwiz/packwiz@latest
        shell: bash

      - name: Format Filename
        id: set-filename
        run: |
          if [ ${{ inputs.type }} != 'release' ]; then
            echo "filename=Feather-V${{ inputs.version }}-${{ matrix.loader }}-${{ inputs.type }}" >> "$GITHUB_OUTPUT"
          else
            echo "filename=Feather-V${{ inputs.version }}-${{ matrix.loader }}" >> "$GITHUB_OUTPUT"
          fi
        shell: bash
      
      - name: Build Modrinth Modpack
        if: ${{ matrix.platform == 'modrinth' }}
        run: |
          packwiz mr export
          mv Feather-${{ inputs.version }}.mrpack ${{ steps.set-filename.outputs.filename }}.mrpack
          echo "FILE=${{ steps.set-filename.outputs.filename }}.mrpack" >> "$GITHUB_ENV"
          echo "Modrinth pack for ${{ matrix.loader}} has been exported as '${{ steps.set-filename.outputs.filename }}.mrpack'"
        shell: bash
        working-directory: ${{matrix.platform}}/${{matrix.loader}}
  
      - name: Build Curseforge Modpack
        if: ${{ matrix.platform == 'curseforge' }}
        run: |
          packwiz cf export
          mv Feather-${{ inputs.version }}.zip ${{ steps.set-filename.outputs.filename }}.zip
          echo "FILE=${{ steps.set-filename.outputs.filename }}.zip" >> "$GITHUB_ENV"
          echo "Curseforge pack for ${{ matrix.loader}} has been exported as '${{ steps.set-filename.outputs.filename }}.zip'"
        shell: bash
        working-directory: ${{matrix.platform}}/${{matrix.loader}}
  
  
      - name: Upload to Release
        run: |
          gh release upload v${{ inputs.version }} $FILE --clobber
          echo "Modpack $FILE has been uploaded to release V${{ inputs.version }}"
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        working-directory: ${{matrix.platform}}/${{matrix.loader}}